// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqgslhagweiqvepjbdmb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZ3NsaGFnd2VpcXZlcGpiZG1iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODYwMDMsImV4cCI6MjA2NTY2MjAwM30.cWFCMZatm51QQFS0QSa__GazHPEaKNe7oDoIFKMHpzk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);